# Generated by Django 5.1.1 on 2024-09-28 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="book title"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="book title"
                    ),
                ),
                (
                    "published_at",
                    models.PositiveIntegerField(
                        default=2024,
                        validators=[
                            django.core.validators.MinValueValidator(1455),
                            django.core.validators.MaxValueValidator(2540),
                        ],
                        verbose_name="year of publication",
                    ),
                ),
            ],
        ),
    ]
