# Generated by Django 5.1.1 on 2024-09-28 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_author_full_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="full_name",
            new_name="name",
        ),
    ]
