# Generated by Django 5.1.1 on 2024-10-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_rename_full_name_author_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_hardcopy_owned",
            field=models.BooleanField(default=False),
        ),
    ]
