# Generated by Django 5.1.1 on 2024-10-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_book_is_hardcopy_owned"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="digital_file",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
