---
- hosts: virtualmachines
  vars_files:
    - vars.yaml
  become: yes
  tasks:
    - name: ping
      ansible.builtin.ping:

    - name: clone
      ansible.builtin.git:
        repo: git@github.com:sirodoht/bookcase.git
        dest: /var/www/bookcase
        version: main
        accept_hostkey: true
      become_user: deploy

    - name: collectstatic
      ansible.builtin.shell:
        cmd: ~/.cargo/bin/uv run manage.py collectstatic --no-input
        chdir: /var/www/bookcase
      args:
        executable: /bin/bash
      become_user: deploy
    - name: migrations
      ansible.builtin.shell:
        cmd: ~/.cargo/bin/uv run manage.py migrate --no-input
        chdir: /var/www/bookcase
      args:
        executable: /bin/bash
      become_user: deploy

    - name: caddyfile
      ansible.builtin.template:
        src: bookcase.caddy.j2
        dest: /etc/caddy/bookcase.caddy
        owner: root
        group: root
        mode: '0644'

    - name: gunicorn restart
      ansible.builtin.systemd:
        name: bookcase
        state: restarted
    - name: caddy restart
      ansible.builtin.systemd:
        name: caddy
        state: restarted
